*Pronounced: `pea-lay Exodus`*
* The Idea
- You track something, and you publish either an artifact or something to indicate proof-of-work.
** Core Principle:
- Promote ~Freedom of Action~ over ~Freedom of Speech not Reach~ (What Elon is doing at X)
* Why?
- Ensure momentum, consistency, accountability, and encourage others.
* How? (options)
- 1: Plain text tracking (~.org~ / ~.md~ / ~.txt~), typically via habit tables.
  - (Or exports (could be redacted) from some sort of tracking system, such as [[https://github.com/ml729/org-habit-stats][org-habit-stats]], [[https://github.com/ml729/calfw-blocks][calfw-blocks]], [[https://github.com/ichernyshovvv/org-timeblock][org-timeblock]], [[https://github.com/Fuco1/org-timeliney][org-timeline]], [[https://github.com/dmitrym0/org-hyperscheduler][org-hyperscheduler]])
- 2: Browsable artifact feed by day for a particular action (say for art/music)
  - (This could maybe be uploaded via a plain text document, with headers for a given day containing a external link to the content artifact. Then this could be hosted at say like ~piletexod.us/user/art~ for a art feed, etc, and these feeds could be listed under their profile in the indexer.)
* Community Indexer (TBD)
- Indexer of individuals participating in this at ~piletexod.us~
  - Add/Remove of individuals automated by their PRs and with merge bot rules.
  - Individual is removed from indexer after 30 days of no activity (no commits in their linked github piletexodus project)
  - (Maybe long-term set this up via a external server, that git clones people repos who are registered, processes their feeds, and hosts them (habit tracking, art, music, etc). If art uploaded say to ipfs or something, then iframe the content - display it from external. Tell people that you'll only process their repo say if it's less than 100MB or something, so that I have enough space to store everyone. So don't put images/videos/content in your piletexodus repo. Link to it externally. Just give me text, structure, and links. We'll process it, and host and present it under your username for you. Also host a readme for them.)
** Additional Fun Features:
*** Leaderboard:
**** (Hardcore) IronMan Mode, and just Generic
- Daily (Post every 2x days, otherwise dropped).
- Weekly (every 8 days latest).
- Sechs (6) (Every 7 days latest)
*** Challenges
- Add other users, to your allowed interactive users list. Then can do challenges (like weekly). Get reports (summaries) regarding everybodies completion, ranking in the competition.
*** Proof-Of-Work Integrations:
- Like for meditation, have a marketplace of verifiers (image recognition, make sure your in frame, etc), then output an attached approval/rejection regarding the successful completion of that activity.
*** Crypto subscriptions to feeds (to artifact production)
- If you like somebody who is making music or art, you can subscribe with a small amount per day, or something. Or queue it up per week (assuming daily post). Or maybe pay 0.00000001bitcoin/20posts, or something.
  - (Current problem with say Github Sponsors, or Patreon, etc, is wtf am I paying for. How do I know I'm not just paying your habit to diddle little children? How do I know your even doing anything? More transparency in output would help in this. So it works such that: I'm providing funding, given progress made in area x, via artifacts uploaded at y amount/frequency. I'm funding the process, less the outcome. The outcome will come.)
*** Wall of Ancestors
- Images of your ancestors, a blurb about them.
- Why: Inspires a spiritual legacy to your genes. Your ancestors were fighting, and produced you. So you have to keep going, and continue the fight, that they left to you. (Romans did this. Also any royal family, people that rule others, do this type of thing. Look at masons as well, it's the "Ancient Babylon Religion".)
