*Pronounced: `pea-lay Exodus`*
* The Idea
- You track something, and you publish either an artifact or something to indicate proof-of-work.
* Why?
- Ensure momentum, consistency, accountability, and encourage others.
* How? (options)
- 1: Plain text tracking (~.org~ / ~.md~ / ~.txt~), typically via habit tables.
  - (Or exports (could be redacted) from some sort of tracking system, such as [[https://github.com/ml729/org-habit-stats][org-habit-stats]], [[https://github.com/ml729/calfw-blocks][calfw-blocks]], [[https://github.com/ichernyshovvv/org-timeblock][org-timeblock]], [[https://github.com/Fuco1/org-timeliney][org-timeline]], [[https://github.com/dmitrym0/org-hyperscheduler][org-hyperscheduler]])
- 2: Browsable artifact feed by day for a particular action (say for art/music)
  - (This could maybe be uploaded via a plain text document, with headers for a given day containing a external link to the content artifact. Then this could be hosted at say like ~piletexod.us/user/art~ for a art feed, etc, and these feeds could be listed under their profile in the indexer.)
* Community Indexer (TBD)
- Indexer of individuals participating in this at ~piletexod.us~
  - Add/Remove of individuals automated by their PRs and with merge bot rules.
  - Individual is removed from indexer after 30 days of no activity (no commits in their linked github piletexodus project)
  - (Maybe long-term set this up via a external server, that git clones people repos who are registered, processes their feeds, and hosts them (habit tracking, art, music, etc). If art uploaded say to ipfs or something, then iframe the content - display it from external. Tell people that you'll only process their repo say if it's less than 100MB or something, so that I have enough space to store everyone. So don't put images/videos/content in your piletexodus repo. Link to it externally. Just give me text, structure, and links. We'll process it, and host and present it under your username for you. Also host a readme for them.)
** Additional Fun Features:
*** Leaderboard:
**** (Hardcore) IronMan Mode, and just Generic
- Daily (Post every 2x days, otherwise dropped).
- Weekly (every 8 days latest).
- Sechs (6) (Every 7 days latest)
*** Challenges
- Add other users, to your allowed interactive users list. Then can do challenges (like weekly). Get reports (summaries) regarding everybodies completion, ranking in the competition.
*** Proof-Of-Work Integrations:
- Like for meditation, have a marketplace of verifiers (image recognition, make sure your in frame, etc), then output an attached approval/rejection regarding the successful completion of that activity.
