*Pronounced: `pea-lay Exodus`*
* The Idea
- You track something, and you publish either an artifact or something to indicate proof-of-work.
* Why?
- Ensure momentum, consistency, accountability, and encourage others.
* How? (options)
- 1: Plain text tracking (~.org~ / ~.md~ / ~.txt~), typically via habit tables.
  - (Or exports (could be redacted) from some sort of tracking system, such as [[https://github.com/ml729/org-habit-stats][org-habit-stats]], [[https://github.com/ml729/calfw-blocks][calfw-blocks]], [[https://github.com/ichernyshovvv/org-timeblock][org-timeblock]], [[https://github.com/Fuco1/org-timeliney][org-timeline]], [[https://github.com/dmitrym0/org-hyperscheduler][org-hyperscheduler]])
- 2: Browsable artifact feed by day for a particular action (say for art/music)
  - (This could maybe be uploaded via a plain text document, with headers for a given day, and a external link to the content. Then this could be hosted at say like ~piletexod.us/user/art~ for a art feed, etc, and these feeds could be listed under their profile in the indexer.)
* Community Indexer (TBD)
- Indexer of individuals participating in this at ~piletexod.us~
  - Add/Remove of individuals automated by their PRs and with merge bot rules.
  - Individual is removed from indexer after 30 days of no activity (no commits in their linked github piletexodus project)
** Additional Fun Features:
*** Leaderboard:
**** (Hardcore) IronMan Mode, and just Generic
- Daily (Post every 2x days, otherwise dropped).
- Weekly (every 8 days latest).
- Sechs (6) (Every 7 days latest)
*** Challenges
- Add other users, to your allowed interactive users list. Then can do challenges (like weekly). Get reports (summaries) regarding everybodies completion, ranking in the competition.
*** Proof-Of-Work Integrations:
- Like for meditation, have a marketplace of verifiers (image recognition, make sure your in frame, etc), then output an attached approval/rejection regarding the successful completion of that activity.
