*Pronounced: 'pea-lay Exodus'*
* The Idea
- You track something, and you publish either an artifact or something to indicate proof-of-work.
* Why?
- Ensure momentum, consistency, and accountability.
* How? (options)
- 1: Plain text table habit tracking (~.org~ / ~.md~ / ~.txt~).
- 2: Browsable artifact feed by day for a particular action (say for art/music)
* Community Indexer (TBD)
- Indexer of individuals participating in this at ~piletexod.us~
  - Add/Remove of individuals automated by their PRs and with merge bot rules.
  - Individual is removed from indexer after 30 days of no activity (no commits in their linked github piletexodus project)
** Additional Fun Features:
*** Leaderboard:
**** IronMan Mode
- Daily (Post every 2x days, otherwise dropped).
- Weekly (every 8 days latest).
- Sechs (6) (Every 7 days latest)
*** Challenges
- Add other users, to your allowed interactive users list. Then can do challenges (like weekly). Get reports (summaries) regarding everybodies completion, ranking in the competition.
*** Proof-Of-Work Integrations:
- Like for meditation, have a marketplace of verifiers (image recognition, make sure your in frame, etc), then output an attached approval/rejection regarding the successful completion of that activity.
